Deprecate golang code
naurffxiv/moddingway pull request #113
Opened 2024-10-09 05:54 UTC by brtran4

2024-11-03 03:46 UTC, KingPieson approved these changes

2024-11-05 13:59 UTC, clairefleuret commented
@brtran4 can you resolve the conflicts and then merge please

2024-11-06 01:31 UTC, OTCompa requested changes
I believe there are still references to golang things in `docker-compose.yml`
`internal/discord/commands.go` and `postgres.override.yml` should be fine to remove too
We can also remove `make format` from the makefile

2024-11-08 20:15 UTC, OTCompa approved these changes

2024-11-08 20:16 UTC, merged