sql code for notes table
naurffxiv/moddingway pull request #207
Opened 2024-12-04 19:27 UTC by oytundd

Ticket:MOD-23

Added required queries for notes table.

2024-12-04 19:37 UTC, KingPieson requested changes

2024-12-04 19:37 UTC, KingPieson commented on postgres/drop_all_tables.sql
> +drop table IF EXISTS notes;
this needs to be dropped before we drop users, because it has a FK of user ID

2024-12-04 19:37 UTC, KingPieson commented on postgres/seed_data.sql
> +delete from notes;
same thing as above, you need to delete notes before you delete users

2024-12-04 19:38 UTC, brtran4 reviewed
nit: i would title the PR for something like "Add notes table to db" or something like that

2024-12-04 20:11 UTC, KingPieson approved these changes

2024-12-05 00:19 UTC, brtran4 reviewed
i think this should be targeted to the 1.1 hotfix branch

2024-12-05 00:34 UTC, oytundd commented
> i think this should be targeted to the 1.1 hotfix branch

i thought i would make a mod-2 branch for notes feature then work on tickets related to mod-2 under this branch then merge when its complete, is this a bad idea

2024-12-05 19:07 UTC, merged