Implement ban command
naurffxiv/moddingway pull request #32
Opened 2024-07-20 06:41 UTC by brtran4

2024-07-20 07:22 UTC, brtran4 commented on internal/discord/commands.go
> +		interaction: i,
this is definitely a problem since it's properly formatted on my IDE, but not here

2024-07-20 17:57 UTC, OTCompa requested changes

2024-07-20 17:57 UTC, OTCompa commented on internal/discord/commands.go
> +		err = StartInteraction(s, i.Interaction, "Please provide a reason for the ban.")
We should try to use `RespondToInteraction()` instead. Discord differentiates between the first respond and any further follow-ups, so any use of `StartInteraction()` after any response will not do anything.

2024-07-21 22:54 UTC, OTCompa approved these changes

2024-07-22 01:09 UTC, merged