Make getting environment variables cleaner
naurffxiv/moddingway pull request #54
Opened 2024-07-23 05:17 UTC by OTCompa

Currently for every environment variable we get, we need to error check like so:
```golang
discordToken, ok := os.LookupEnv("DISCORD_TOKEN")
if !ok {
  panic("You must supply a DISCORD_TOKEN to start!")
}

guildID, ok := os.LookupEnv("GUILD_ID")
if !ok {
  panic("You must supply a GUILD_ID to start!")
}

modLoggingChannelID, ok := os.LookupEnv("MOD_LOGGING_CHANNEL_ID")
if !ok {
  panic("You must supply a MOD_LOGGING_CHANNEL_ID to start!")
}

// rest of the env vars
```

This helper will allow us to simplify it slightly and move error checking to right before we start any connections.
```golang
discordToken := eg.GetEnv("DISCORD_TOKEN")
guildID := eg.GetEnv("GUILD_ID")
modLoggingChannelID := eg.GetEnv("MOD_LOGGING_CHANNEL_ID")

// rest of the env vars

if !eg.Ok {
  tempstr := fmt.Sprintf("You must supply a %s to start!", eg.EnvName)
  panic(tempstr)
}
```

2024-07-23 05:23 UTC, brtran4 commented
will this PR include actually using that? or will that be in a chained PR?

2024-07-23 06:44 UTC, OTCompa commented
> will this PR include actually using that? or will that be in a chained PR?

It'll be in a chained PR. I didn't want to make the PR further down the line too big so I figured I'd split it into smaller one

2024-07-23 06:57 UTC, brtran4 commented
> > will this PR include actually using that? or will that be in a chained PR?
> 
> It'll be in a chained PR. I didn't want to make the PR further down the line too big so I figured I'd split it into smaller one. I can also update the current `main.go` in this PR too since it'll have to be done later anyway if that's cool

i think the change is small enough where we can fit it into one PR

2024-07-23 20:28 UTC, brtran4 requested changes

2024-07-23 20:28 UTC, brtran4 commented on main.go
> +	discordToken = strings.TrimSpace(discordToken)
we could just move this into `GetEnv` since all strings will hit this case

2024-07-24 00:21 UTC, brtran4 approved these changes

2024-07-24 06:56 UTC, merged