sql-exile
naurffxiv/moddingway pull request #55
Opened 2024-07-23 05:52 UTC by OTCompa

2024-07-23 07:08 UTC, brtran4 commented
> This PR adds the `exiles` table to the database schema. It will be used to check when people should be automatically unexiled after the exile duration is over. It also fixes some minor formatting/spelling issues in the original SQL files.
> 
> The `exileStatus` column will be defined using an enum that's included in this PR. The names for each enum aren't really that good, so feel free to suggest better ones.
> 
> * `Unexiled` means the user has been unexiled already.
> * `IndefiniteExile` means a duration was not set for the exile
> * `TimedExile` means a current exile that either is still in effect or has yet to be unexiled
> * `TimedExileMissing` means a user was exiled with a duration, but they have left the server before they were unexiled (to prevent repeated attempts to unexile them when they aren't in the server)

i think we should drop the entry if the user has been unexiled. @clairefleuret do we want to store the amount of exiles a person accumulated?

just a funny thought, but we can rename `TimedExileMissing` to `Runaway` since they're "running" away from the exile 😝

2024-07-23 13:55 UTC, clairefleuret commented
> i think we should drop the entry if the user has been unexiled. @clairefleuret do we want to store the amount of exiles a person accumulated?

Nah, strikes being tracked is what we care about.

2024-07-23 20:29 UTC, brtran4 requested changes
yeah let's drop the entries if they are unexiled

2024-07-24 06:24 UTC, brtran4 approved these changes

2024-07-24 06:56 UTC, merged