Add LogCommand function to log used commands to a specific channel
naurffxiv/moddingway pull request #6
Opened 2024-06-07 01:28 UTC by OTCompa

Dependent on #5

2024-06-07 03:22 UTC, OTCompa commented
From the issue in #2:
> let's double check that it does not send ephemeral messages
The `LogCommand` function shouldn't send any ephemeral messages at all, it will only send an embed to the specified log channel. Ephemeral responses are sent by the slash command function. (Correct me if I'm misunderstanding something)

2024-06-07 17:47 UTC, brtran4 commented
> From the issue in #2:
> 
> > let's double check that it does not send ephemeral messages
> 
> The `LogCommand` function shouldn't send any ephemeral messages at all, it will only send an embed to the specified log channel. Ephemeral responses are sent by the slash command function. (Correct me if I'm misunderstanding something)

as long as you've tested and the embed isn't ephemeral then that looks good to me :)

2024-06-07 18:11 UTC, brtran4 requested changes

2024-06-07 18:11 UTC, brtran4 commented on main.go
> +		ModLogChannelID: "",
let's also move this to https://github.com/naurffxiv/moddingway/pull/5

2024-06-07 20:29 UTC, OTCompa commented on internal/discord/command-handlers.go
> +		},
![image](https://github.com/naurffxiv/moddingway/assets/41562938/b4a89200-1797-49bb-8558-022e4a62fba6)

2024-06-08 05:32 UTC, brtran4 approved these changes

2024-06-08 05:32 UTC, merged